########################################################################################
# Infos: https://community.home-assistant.io/t/esp32-s3-1-8inch-amoled-touch/956270/12 #
########################################################################################

globals:
  - id: last_mic_pub
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: mic_warmup_until
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: top_button_counter
    type: int
    restore_value: yes
    initial_value: '0'

esphome:
  name: esp32-s3-touch-amoled-18
  friendly_name: ESP32-S3-Touch-AMOLED-1.8
  on_boot:
    priority: -10
    then:
      - lambda: |-
          id(my_display).set_brightness((uint8_t) id(disp_brightness).state);

esp32:
  variant: esp32s3
  framework:
    type: esp-idf
  flash_size: 16MB

psram:
  mode: octal

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  - platform: esphome
    password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.***
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1    

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
########################################################################################
# Infos: https://community.home-assistant.io/t/esp32-s3-1-8inch-amoled-touch/956270/12 #
########################################################################################

globals:
  - id: last_mic_pub
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: mic_warmup_until
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: top_button_counter
    type: int
    restore_value: yes
    initial_value: '0'

esphome:
  name: esp32-s3-touch-amoled-18
  friendly_name: ESP32-S3-Touch-AMOLED-1.8
  on_boot:
    priority: -10
    then:
      - lambda: |-
          id(my_display).set_brightness((uint8_t) id(disp_brightness).state);

esp32:
  variant: esp32s3
  framework:
    type: esp-idf
  flash_size: 16MB

psram:
  mode: octal

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "w+1bGpPMfqOBKlZf99Y3XfBvhaDO5bp6zMSLJ7UOp7Q="

ota:
  - platform: esphome
    password: "a28f650a3f3eec43718895b510172397"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.197
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1    

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-S3-Touch-Amoled-18"
    password: "5wrXB2fqBWDs"

captive_portal:
    
web_server:
  port: 80

###########################################################################

# I2C Bus - Shared by touchscreen (FT5x06) and audio codec (ES8311)
i2c:
  id: i2c_bus
  sda: GPIO15
  scl: GPIO14
  frequency: 200kHz # 400kHz # 200kHz
  scan: true

# Quad SPI Bus - AMOLED display
spi:
  - id: quad_spi
    type: quad
    clk_pin: GPIO11
    data_pins:
      - GPIO4   # D0
      - GPIO5   # D1
      - GPIO6   # D2
      - GPIO7   # D3

pca9554:
  - id: pca9554_device
    address: 0x20
    i2c_id: i2c_bus

display:
  - platform: mipi_spi
    id: my_display
    brightness: 255
    bus_mode: quad
    dimensions:
      width: 368
      height: 448
    model: WAVESHARE-ESP32-S3-TOUCH-AMOLED-1.75
    cs_pin: GPIO12
    reset_pin:
      pca9554: pca9554_device
      number: 0

touchscreen:
  - platform: cst816
    id: my_touchscreen
    display: my_display
    i2c_id: i2c_bus
    address: 0x38
    interrupt_pin: GPIO21
    reset_pin:
      pca9554: pca9554_device
      number: 1        # EXIO0
    skip_probe: true
    on_touch:
      - logger.log:
          format: "Touch: x=%d y=%d"
          args: [touch.x, touch.y]

# ============================================================================
# AUDIO CONFIGURATION
# ============================================================================

# I2S Audio Bus - Connects ESP32 to ES8311 codec
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO45   # Word select / left-right clock
    i2s_bclk_pin: GPIO9     # Bit clock
    i2s_mclk_pin: GPIO16    # Master clock

# ES8311 Audio Codec
audio_dac:
  - platform: es8311
    id: es8311_codec
    address: 0x18
    i2c_id: i2c_bus
    use_mclk: true
    use_microphone: False
    mic_gain: 24DB

# Speaker - Audio output through ES8311 DAC
speaker:
  - platform: i2s_audio
    id: external_speaker
    dac_type: external
    audio_dac: es8311_codec
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO8
    sample_rate: 16000
    bits_per_sample: 16bit
    timeout: 2s

# Microphone - Audio input through ES8311 ADC
sensor:
  - platform: template
    name: "Mic RMS"
    id: mic_rms
    accuracy_decimals: 0
    update_interval: never

  - platform: template
    name: "Mic Peak"
    id: mic_peak
    accuracy_decimals: 0
    update_interval: never

  - platform: adc
    pin: GPIO1          # Beispiel! Richtigen Pin einsetzen
    id: battery_voltage
    name: "Battery Voltage 1"
    attenuation: 11db
    update_interval: 30s
    filters: [] 

  - platform: adc
    pin: GPIO3          # Beispiel! Richtigen Pin einsetzen
    id: battery_voltage_3
    name: "Battery Voltage 3"
    attenuation: 11db
    update_interval: 30s
    filters: [] 

  - platform: adc
    pin: GPIO2
    id: battery_voltage_raw
    name: "Battery Voltage: raw"
    attenuation: 11db
    update_interval: 30s
    raw: true

  - platform: template
    name: Battery Level
    unit_of_measurement: "%"
    accuracy_decimals: 1
    lambda: |-
      float v = id(battery_voltage).state;
      if (v >= 4.20) return 100.0;
      if (v >= 4.10) return 90.0  + (v-4.10)*100.0;      // 4.10..4.20
      if (v >= 4.00) return 75.0  + (v-4.00)*150.0;      // 4.00..4.10
      if (v >= 3.90) return 55.0  + (v-3.90)*200.0;      // 3.90..4.00
      if (v >= 3.80) return 35.0  + (v-3.80)*200.0;      // 3.80..3.90
      if (v >= 3.70) return 20.0  + (v-3.70)*150.0;      // 3.70..3.80
      if (v >= 3.60) return 10.0  + (v-3.60)*100.0;      // 3.60..3.70
      if (v >= 3.50) return 5.0   + (v-3.50)*50.0;       // 3.50..3.60
      if (v >= 3.30) return 1.0   + (v-3.30)*20.0;       // 3.30..3.50
      if (v >= 3.10) return 0.5   + (v-3.10)*15.0;       // 3.10..3.40
      return 0.0;

  - platform: template
    name: "Top Button Counter"
    id: top_button_counter_sensor
    accuracy_decimals: 0

microphone:
  - platform: i2s_audio
    id: external_microphone
    adc_type: external
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: GPIO10
    bits_per_sample: 32bit
    sample_rate: 16000
    channel: right
    i2s_mode: primary
    on_data:
      - lambda: |-
          const int32_t *s = (const int32_t*) x.data();
          const size_t n = x.size() / sizeof(int32_t);
          if (n == 0) return;
          int32_t peak = 0;
          uint64_t acc = 0;
          for (size_t i = 0; i < n; i++) {
            int32_t v = s[i] >> 8;   // 32 → 24 Bit
            v = v >> 8;              // 24 → 16 Bit
            int32_t av = v < 0 ? -v : v;
            if (av > peak) peak = av;
            acc += (uint64_t)((int64_t)v * (int64_t)v);
          }
          const uint32_t now = millis();
          if (now - id(last_mic_pub) < 1000) return;  // 1 Sekunde
          id(last_mic_pub) = now;
          uint32_t rms = (uint32_t) sqrt((double)acc / (double)n);
          id(mic_peak).publish_state((float) peak);
          id(mic_rms).publish_state((float) rms);


# Volume Control - Synced with ES8311 hardware volume and UI slider
number:
  - platform: template
    id: volume_control
    name: "Volume"
    min_value: 0
    max_value: 100
    initial_value: 70
    step: 5
    optimistic: true
    set_action:
      - lambda: |-
          id(es8311_codec).set_volume(x / 100.0);
          ESP_LOGI("volume", "Volume set to: %.0f%%", x);

# Hellichkeit regelbar machen
  - platform: template
    name: "Display Brightness"
    id: disp_brightness
    min_value: 0
    max_value: 255
    step: 1
    initial_value: 255
    optimistic: true
    set_action:
      - lambda: |-
          id(my_display).set_brightness((uint8_t) x);


# RTTTL Ringtone Player - Plays simple tones and melodies
rtttl:
  id: buzzer
  speaker: external_speaker

# ============================================================================
# VOICE ASSISTANT
# ============================================================================

voice_assistant:
  id: va
  microphone: external_microphone
  speaker: external_speaker

  # Listening state - Button turns blue
  on_listening:
    - logger.log: "Voice assistant started listening"
    - lvgl.label.update:
        id: status_label
        text: "Listening..."
    - lvgl.widget.update:
        id: btn_id
        bg_color: DodgerBlue

  # Speech-to-text complete - Display recognized text
  on_stt_end:
    - logger.log:
        format: "Speech recognized: %s"
        args: [ 'x.c_str()' ]
    - lvgl.label.update:
        id: status_label
        text: !lambda 'return "You said: " + x;'

  # Text-to-speech starting - Display speaking status
  on_tts_start:
    - logger.log: "Speaking response..."
    - lvgl.label.update:
        id: status_label
        text: "Speaking..."

  # Session complete - Button returns to green
  on_end:
    - logger.log: "Voice assistant session ended"
    - lvgl.label.update:
        id: status_label
        text: "Ready"
    - lvgl.widget.update:
        id: btn_id
        bg_color: LightGreen

  # Error handling - Flash red, then return to green
  on_error:
    - logger.log:
        format: "Voice assistant error: %s"
        args: [ 'code.c_str()' ]
    - lvgl.label.update:
        id: status_label
        text: "Error!"
    - lvgl.widget.update:
        id: btn_id
        bg_color: Red
    - delay: 1s
    - lvgl.widget.update:
        id: btn_id
        bg_color: LightGreen
    - lvgl.label.update:
        id: status_label
        text: "Ready"

# ============================================================================
# USER INTERFACE (LVGL)
# ============================================================================

font:
  - file: "gfonts://Roboto"
    id: font_large
    size: 32

  - file: "gfonts://Roboto"
    id: font_medium
    size: 22

lvgl:
  pages:
    - id: main_page
      bg_color: black
      widgets:
        # Status label - Shows current voice assistant state
        - label:
            id: status_label
            align: CENTER
            y: 50
            text: 'Ready'
            text_color: white
            text_font: font_large

        # Main voice assistant button - Tap to activate
        - button:
            bg_color: LightGreen
            radius: 35          # ← Ecken abrunden (px)            
            x: 84
            y: 100
            width: 200
            height: 140
            id: btn_id
            widgets:
              - label:
                  align: center
                  text: "Tap to Talk"
                  text_color: black
                  text_font: font_large

            on_click:
              then:
                - if:
                    condition:
                      not: voice_assistant.is_running
                    then:
                      - rtttl.play: 'beep:d=16,o=5,b=100:c6'
                      - delay: 500ms
                      - voice_assistant.start:
                    else:
                      - logger.log: "Ignored tap: Voice Assistant already running"

        # Volume slider - Vertical slider on left side
        - slider:
            id: volume_slider
            x: 20
            y: 20
            width: 30
            height: 365
            pad_all: 8
            min_value: 0
            max_value: 100
            value: 70
            on_value:
              then:
                - logger.log:
                    format: "Volume slider: %d"
                    args: [ x ]
                - number.set:
                    id: volume_control
                    value: !lambda 'return x;'

        # Volume label
        - label:
            x: 24
            y: 400
            text_color: white
            text_font: font_large
            text: "V"

        - label:
            id: counter_label
            x: 340
            y: 20
            text: "0"
            text_color: white
            text_font: font_large

################################################ MGC ##################################################

switch:
  - platform: template
    name: "Top Button"
    id: boot_toggle
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: "Lower Toggle"
    id: lower_toggle
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  # Power Amplifier - GPIO46 controls speaker amplifier enable
  - platform: gpio
    pin: GPIO46
    id: pa_enable
    name: "Speaker Amplifier"
    restore_mode: ALWAYS_ON
    internal: false    

binary_sensor:
  - platform: gpio
    name: "Top Button"
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 20ms
    on_press:
      - lambda: |-
          id(top_button_counter) = (id(top_button_counter) + 1) % 6;  // 0..5
      - lvgl.label.update:
          id: counter_label
          text: !lambda |-
            char buf[8];
            snprintf(buf, sizeof(buf), "%d", id(top_button_counter));
            return std::string(buf);
